# Generated by Django 4.2.1 on 2023-05-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_country_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
    ]
