# Generated by Django 4.2.1 on 2023-05-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
