# Generated by Django 4.2.1 on 2023-05-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
