# Generated by Django 4.2.1 on 2023-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
