# Generated by Django 4.2.1 on 2023-05-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_country_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
